SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH FROM MEMBER_PROFILE
WHERE TLNO is not null and month(DATE_OF_BIRTH) = 03 and GENDER = 'W'
ORDER BY MEMBER_ID asc;